services:
  - type: web
    name: africa-backend-gbodo255
    env: python
    rootDir: "AFRICA-PROJECT-BACKEND-main/africa_project"
    buildCommand: "./build.sh"
    startCommand: "sh run.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: africa_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: DATABASE_URL
        value: postgresql://postgres:Naomie334%2FChris123@db.nzoxcdzytohijlcsxmjo.supabase.co:5432/postgres
      - key: ALLOWED_HOSTS
        value: africalogistiquestotalafrica-backend.onrender.com,africa-logistiques-total.vercel.app,.render.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://africa-logistiques-total.vercel.app
