# Generated by Django 5.2.10 on 2026-03-08 11:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africa_logistic', '0002_remove_passwordresettoken_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('INVESTIGATING', 'En investigation'), ('ESCALATED', 'Escaladé'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', max_length=20)),
                ('category', models.CharField(choices=[('DELAY', 'Retard de livraison'), ('DAMAGE', 'Marchandise endommagée'), ('LOSS', 'Perte de marchandise'), ('PAYMENT', 'Problème de paiement'), ('BEHAVIOR', 'Comportement inapproprié'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('description', models.TextField(help_text='Description du litige')),
                ('resolution', models.TextField(blank=True, help_text='Résolution du litige', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_moderator', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MODERATOR', 'MODERATEUR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to='africa_logistic.user')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to='africa_logistic.user')),
                ('transport_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='africa_logistic.transportrequest')),
            ],
            options={
                'verbose_name': 'Litige',
                'verbose_name_plural': 'Litiges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('is_moderator_note', models.BooleanField(default=False, help_text='Note interne modérateur')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='africa_logistic.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages', to='africa_logistic.user')),
            ],
            options={
                'verbose_name': 'Message de litige',
                'verbose_name_plural': 'Messages de litiges',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant minimum: 1000 FCFA', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))])),
                ('method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire')], default='MOBILE_MONEY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('COMPLETED', 'Traitée')], default='PENDING', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to='africa_logistic.user')),
                ('transporter', models.ForeignKey(limit_choices_to={'role': 'TRANSPORTEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='africa_logistic.user')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ['-created_at'],
            },
        ),
    ]
