# Generated by Django 5.2.10 on 2026-03-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africa_logistic', '0003_dispute_disputemessage_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('VALIDATE', 'Validation'), ('REJECT', 'Rejet'), ('ASSIGN', 'Assignation'), ('DISPUTE_RESOLVE', 'Résolution de litige'), ('WALLET_TOPUP', 'Recharge portefeuille'), ('WITHDRAWAL_PROCESS', 'Traitement de retrait')], max_length=20)),
                ('resource_type', models.CharField(help_text='Ex: User, TransportRequest, WalletTransaction', max_length=50)),
                ('resource_slug', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, help_text='Données de la requête pour débogage', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='africa_logistic.user')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]
